import { AgentReviewOutput, Finding, Severity } from '../../agents/types';
import { StateAnnotation } from '../state';

const SEVERITY_ORDER: Severity[] = ['critical', 'high', 'medium', 'low'];

function formatFinding(f: Finding): string {
  const location = f.lineNumber !== null ? `${f.filePath}:${f.lineNumber}` : f.filePath;
  const suggestion = f.suggestion ? `\n  - Suggestion: ${f.suggestion}` : '';
  return `- **${f.title}** (\`${location}\`)\n  - ${f.description}${suggestion}`;
}

function groupBySeverity(findings: Finding[]): string {
  const groups = SEVERITY_ORDER.map((severity) => ({
    severity,
    items: findings.filter((f) => f.severity === severity),
  })).filter((g) => g.items.length > 0);

  if (groups.length === 0) return '_No issues found._';

  return groups
    .map(
      (g) =>
        `**${g.severity[0].toUpperCase()}${g.severity.slice(1)}**\n\n${g.items
          .map(formatFinding)
          .join('\n')}`
    )
    .join('\n\n');
}

function computeVerdict(findings: Finding[]): 'REJECTED' | 'NEEDS CHANGES' | 'APPROVED' {
  if (findings.some((f) => f.severity === 'critical')) return 'REJECTED';
  if (findings.some((f) => f.severity === 'high')) return 'NEEDS CHANGES';
  return 'APPROVED';
}

function agentSection(name: string, review: AgentReviewOutput | null): string {
  if (!review) return `### ${name}\n\n_Agent did not run._`;
  return `### ${name} (score: ${review.score}/10)\n\n${groupBySeverity(review.findings)}`;
}

export async function synthesizerNode(
  state: typeof StateAnnotation.State
): Promise<Partial<typeof StateAnnotation.State>> {
  const { qualityReview, securityReview, performanceReview } = state;

  const allFindings = [
    ...(qualityReview?.findings ?? []),
    ...(securityReview?.findings ?? []),
    ...(performanceReview?.findings ?? []),
  ];

  const scores = [qualityReview?.score, securityReview?.score, performanceReview?.score].filter(
    (s): s is number => typeof s === 'number'
  );
  const overallScore =
    scores.length > 0
      ? Math.round((scores.reduce((a, b) => a + b, 0) / scores.length) * 10) / 10
      : 0;

  const verdict = computeVerdict(allFindings);

  const mustFix = allFindings.filter((f) => f.severity === 'critical' || f.severity === 'high');
  const mustFixSection =
    mustFix.length > 0
      ? mustFix.map(formatFinding).join('\n')
      : '_Nothing blocking — no critical or high severity findings._';

  const finalReview = `## Code Review Summary

**Verdict:** ${verdict}
**Overall Score:** ${overallScore}/10

${agentSection('Code Quality', qualityReview)}

${agentSection('Security', securityReview)}

${agentSection('Performance', performanceReview)}

## Must Fix Before Merge

${mustFixSection}

---
_Automated first-pass review generated by three specialized agents (quality, security, performance). Use judgment — this does not replace human review._`;

  return { finalReview, overallScore, verdict };
}
